{$op_names = [
	'BONUS'=>'Bonus',
	'PENALTY'=>'Penalty',
	'CASHIN'=>'Add funds',
	'CASHOUT'=>'Withdraw',
	'EX'=>'Exchange',
	'EXIN'=>'Exchange in',
	'TR'=>'Transfer',
	'TRIN'=>'Transfer in',
	'BUY'=>'Buy',
	'SELL'=>'Sell',
	'BUY2'=>'Buy',
	'SELL2'=>'Sell',
	'REF'=>'Referral',
	'GIVE'=>'Deposit',
	'TAKE'=>'Removal',
	'CALCIN'=>'Profit',
	'CALCOUT'=>'Deduction'
] scope='global'}
{$op_statuses = [
	0=>'Prepeared',
	1=>'Waiting confirmation',
	2=>'Pending',
	3=>'Complete',
	4=>'Rejected',
	5=>'Canceled'
] scope='global'}
{$op_sums = [
	'BONUS'=>'Amount',
	'PENALTY'=>'Amount',
	'CASHIN'=>'Amount to add',
	'CASHOUT'=>'Amount to withdraw',
	'EX'=>'Amount to exchange',
	'EXIN'=>'Received amount',
	'TR'=>'Amount to receive',
	'TRIN'=>'Received amount',
	'BUY'=>'Amount',
	'SELL'=>'Amount',
	'BUY2'=>'Amount',
	'SELL2'=>'Amount',
	'REF'=>'Amount',
	'GIVE'=>'Deposit amount',
	'TAKE'=>'Amount to receive',
	'CALCIN'=>'Amount',
	'CALCOUT'=>'Amount'
] scope='global'}
